# permissions for end users to edit printers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hello-operator
    app.kubernetes.io/managed-by: kustomize
  name: printer-editor-role
rules:
- apiGroups:
  - tutorial.optutorial
  resources:
  - printers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tutorial.optutorial
  resources:
  - printers/status
  verbs:
  - get
