---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tutorial.optutorial
  resources:
  - printers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tutorial.optutorial
  resources:
  - printers/finalizers
  verbs:
  - update
- apiGroups:
  - tutorial.optutorial
  resources:
  - printers/status
  verbs:
  - get
  - patch
  - update
